# Shared file included by the makefiles used to build packages.
# This contains various information needed by the makefiles,
# and is autogenerated by configure to include various
# necessary details.

# Tools needed:

CC = /home/stark/arm-2011.03/bin/arm-none-linux-gnueabi-gcc
STRIP = strip
LDFLAGS = -L/home/stark/HPwebOS/PDK/device/lib -Wl,-rpath-link,/home/stark/HPwebOS/PDK/device/lib -Wl,--dynamic-linker=/lib/ld-linux.so.3 -lpdl -static-libgcc -L/home/stark/HPwebOS/PDK/device/lib -lSDL

# Package name and version number:

PACKAGE = sdl-sopwith
PACKAGE_NAME = SDL Sopwith
PACKAGE_STRING = SDL Sopwith 2.9.0
PACKAGE_TARNAME = sdl-sopwith
PACKAGE_VERSION = 2.9.0

DOC_FILES = README.md COPYING.md FAQ.md NEWS.md

